### ISSUE TITLE
FirstConfiguration doesn't work on 1.1.4

### ISSUE THREAD

**Issue by ldesomer** [arduino-libraries/MKRWAN#11]
Hi,
First Configuration sketch doesn't work on fw 1.1.4. Whatever the value you set to appKey and appEui the int "connected" will be equal to 1, even if you're not connected. Same problem when using ABP instead of OTAA.

**Comment by facchinm** [comment]
Hi @ldesomer ,
I just tested it, and if I enter bogus data I always get 
```
Error sending message :(
```
but `connected()` returns true. While it's normal in ABP mode, it shouldn't in OTAA.
The FW only returns the joined event when the state machine enters `DEVICE_STATE_JOINED` status, so there is something wrong there

**Comment by facchinm** [comment]
Fixed by 05f9804, thanks for reporting!

**Comment by ldesomer** [comment]
Thanks for your quick reply and your help @facchinm !
