### ISSUE TITLE
USB disconnecting when connecting via modem.joinOTAA

### ISSUE THREAD

**Issue by arknoto** [arduino-libraries/MKRWAN#121]
Weird issue that I have narrowed down to when the lora modem attempts to connect OTAA.  My code will execute and then disconnect USB, windows will say usb not recognized device I will loose serial connection and the code will stop running.  Weird part is the exact same sketch runs on the second board I have without any issue.  

Thoughts? Has anyone encountered this?

**Comment by per1234** [comment]
Hi @arknoto. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
