### ISSUE TITLE
MKRWANFWUpdate_standalone - firmware 1.1.4 instead of 1.1.5 or "label" error?

### ISSUE THREAD

**Issue by MarcoBenini** [arduino-libraries/MKRWAN#14]
I upgraded the library in Arduino IDE to 1.03 release.
At the end of firmware update, when is checked the firmware version (modem->version()) the version shown is "ARD-078 1.1.4 " instead of 1.1.5.

**Comment by MarcoBenini** [comment]
Not using Arduino IDE upgrade, but downloading from GitHub the library files solves the problem.

**Comment by facchinm** [comment]
Hi @MarcoBenini ,  I forgot to push the new tag after updating the FW to 1.1.5; fixing right now with https://github.com/arduino-libraries/MKRWAN/releases/tag/1.0.4
