### ISSUE TITLE
Problem with write function

### ISSUE THREAD

**Issue by ldesomer** [arduino-libraries/MKRWAN#17]
Hi,
I think there's an issue with the modem.write(payload) function.
If we consider payload=123456, in hex payload=1E240.
But when I take a look on my server where the payloads are stored. The value of the payload is: 40E201.
How can we fix that ?
Thanks for your help.

**Comment by facchinm** [comment]
Hi @ldesomer ,
it is totally expected. `modem.write(int)` is inherited from Print class, which has no idea of the internal bytes order and converts an int to a byte buffer, so the resulting buffer is "inverted". The usual approach, when dealing with endiannes and data that doesn't fit an uint8_t is to manually specify the byte order when sending.
Eg:
```
uint8_t buffer[4];
buffer[0]=payload & 0xFF;
buffer[1]=(payload >> 8) & 0xFF;
buffer[2]=(payload >> 16) & 0xFF;
buffer[3]=(payload >> 24) & 0xFF;
modem.write(buffer, 4);
```
