### ISSUE TITLE
Transmission distance btw MKRWAN

### ISSUE THREAD

**Issue by yijenlu1971** [arduino-libraries/MKRWAN#24]
Hi,
My question is how far the transmission distance between two MKRWAN boards (only point to point). I tested them about 250 to 300m, is that right ? The receiver got RSSI about -52 to -62 with a side-by-side sender. It says that LoRa can transmit data far far away, even more than 2km. Why arduino MKRWAN not ? Is there anything wrong with my code setting ?
Thanks.

**Comment by MITEL-UNIUD** [comment]
In my own experiments, the antenna is crucial (type and position). I was able to be received by gateways as far as 27,5km, but likely they have hundreds dollars antennas on top of a high roof. My own single channel gateway, with a simple antenna, can be reached up to about 1km if outdoors, much less if indoors.
