### ISSUE TITLE
Network Join Request timeout too long for SAMD watchdog

### ISSUE THREAD

**Issue by sslupsky** [arduino-libraries/MKRWAN#37]
The join request has a timeout of 60 seconds:

```
  bool join() {
    sendAT(GF("+JOIN"));
    if (waitResponse(60000L, "+EVENT=1,1") != 1) {
      return false;
    }
    return true;
  }
```

Is there a reason it is so long?  This causes a problem when using a watchdog.  The maximum timeout for the watchdog is 16 seconds.  So, if the network join request is sent and the node doesn't join, the watchdog times out and reboots.

Can I safety reduce the timeout to something around 10 seconds?

**Comment by facchinm** [comment]
I was using 60 seconds as per Murata specifications (on their closed source firmware) but probably this timeout can be reduced. However, I strongly suggest you to add a hook in `waitResponse` and reset the watchdog there (for example by defining `YIELD` before the file inclusion 
https://github.com/arduino-libraries/MKRWAN/blob/master/src/MKRWAN.h#L165 )
