### ISSUE TITLE
analogWrite() issue - not switching to digitalWrite

### ISSUE THREAD

**Issue by Gerriko** [arduino-libraries/MKRWAN#44]
I am using an MKR WAN 1300 board.
According to the reference: https://www.arduino.cc/reference/en/language/functions/analog-io/analogwrite/

> After a call to analogWrite(), the pin will generate a steady square wave of the specified duty cycle until the next call to analogWrite() (or a call to digitalRead() or digitalWrite()) on the same pin.

In my case, when I use analogWrite it ignores my subsequent digitalWrite.

Here is my test case. It does not turn off my LED, which I have attached to pin 5.

```
void setup() {
  // put your setup code here, to run once:
  pinMode(5, OUTPUT);

  analogWrite(5, 10);
  delay(5000);
  digitalWrite(5, LOW);
}

void loop() {
  // put your main code here, to run repeatedly:

}
```

**Comment by facchinm** [comment]
Hi @Gerriko ,
on SAMD platform (as the MKRWAN) calling `analogWrite` changes the pin functionality (this doesn't apply to AVR architecture) so `pinMode(OUTPUT)` must be called to switch back to digital mode.

This will work as expected:
```
void setup() {
  // put your setup code here, to run once:
  pinMode(5, OUTPUT);

  analogWrite(5, 10);
  delay(5000);
  pinMode(5, OUTPUT);
  digitalWrite(5, LOW);
}
```
The documentation should be updated to reflect this, or the core modified to automatically switch back to digital mode.
@cmaglie @sandeepmistry

**Comment by sandeepmistry** [comment]
We also have this issue in the core to track this: https://github.com/arduino/ArduinoCore-samd/issues/385
