### ISSUE TITLE
"FirstConfiguration" ABP not working

### ISSUE THREAD

**Issue by TechNyquist** [arduino-libraries/MKRWAN#57]
Hello everyone,

First things first: **Arduino MKRWAN 1300**, firmware just updated to **ARD-078 1.1.9**, and MKRWAN library **1.0.10** .

For me ABP join using bare "First configuration" example fails, while OTAA 1.0 works nicely.
Is it just me or that happens to you too?

**Comment by facchinm** [comment]
Hi @TechNyquist ,
this is quite strange... Which network are you trying to connect to?

**Comment by TechNyquist** [comment]
Hello @facchinm ,
I'm using a local dev LoRaServer framework, with two gateways.

**Comment by facchinm** [comment]
It doesn't indeed. We tested ABP with TTN and the Arduino Pro gateway (A2A network) and they both work correctly. Probably it's a LoRaServer issue? [This](https://github.com/brocaar/loraserver/issues) should be the right place to report it

**Comment by TechNyquist** [comment]
Ok, thank you for your feedback (LoRa is pretty difficult to debug), I'll ping them.
I'm closing this issue and I'd reopen it whenever should the lights fall back here again.
Good job.

**Comment by TechNyquist** [comment]
Ok, sorry everyone, it was my fault.
I was facing a simple frame counter validation issue. Just needed to set the right counter value with "setFCU" and all worked. Thanks and sorry.

For anyone facing this on the same environment, I redirect you to [this LoRaServer forum post](https://forum.loraserver.io/t/error-device-session-does-not-exist-or-invalid-fcnt-or-mic/379/30) that might give you all the required clues to understand and solve why ABP activation is not working.
