### ISSUE TITLE
MKRWAN1300 FW stuck

### ISSUE THREAD

**Issue by gavriil07** [arduino-libraries/MKRWAN#82]
I'm trying to send sensor data using LoRA and MKRWAN1300. The LoRa Sender example fails to begin.
I read I need to do a FW first, but it gets stuck after I enter a key:
![dsa](https://user-images.githubusercontent.com/28069262/104810699-183f2300-57ff-11eb-9481-47c967760756.PNG)

Any ideas?

**Comment by zougloub** [comment]
I got that board for a friend and started playing with it before he does, noticed the same issue as you, so I ended up using the FWUpdaterBridge sketch and a modified stm32flash ( https://sourceforge.net/p/stm32flash/tickets/118/ ).

**Comment by rogeralthaus** [comment]
I had the same problem...

After remove  of port.flush() line  the update was successful...
![Unbenannt](https://user-images.githubusercontent.com/16516810/105726221-1fb2aa80-5f2a-11eb-8d42-c22655948640.PNG)

**Comment by nrcrast** [comment]
I've also had success lowering the baud rate.

**Comment by facchinm** [comment]
Hi everyone, the issue was indeed in `flush()` call. We released a fix by commenting that function (https://github.com/arduino-libraries/MKRWAN/commit/049391822099dae9db67a9ad11f4a2005e745547) but it will be solved at core leven in the next few days too.
